#!/usr/bin/env python3
##########################################################################
# © IBM Confidential
# PID:  5900-BD6, 5900-BBE
# © Copyright IBM Corp. 2024
##########################################################################

version: "1.0.4"
concert:  
  output:  
    # Defines the directory where the processed catalog data will be saved. In this case, it's "catalogs/".
    dir: catalogs/  
    # Indicates whether existing files in the output directory should be overwritten. If true, old files will be replaced.
    overwrite: true  

  catalog:  
    # Sets the title of the catalog being processed.
    title: Custom Catalog Test  
    # Specifies the version of the catalog being processed. It helps in version control for catalog files.
    version: 0.1  

  columns:  
    # Maps the "Control Family" column in the input file. This identifies a group of controls. Required field.
    control_family: Control Family  
    # Maps the "Control Code" column, which represents a unique identifier for each control. Required field.
    control_id: Control Code  
    # Maps the "Control Name" column, which contains the name of the control. Required field.
    control_name: Control Name  
    # Maps the "Control Description" column, containing a detailed description of the control. Required field.
    control_description: Control Description  
    # Maps the "Related Controls" column, which lists other controls related to the one being processed. Optional field.
    related_controls: Related Controls  
